name: Deploy Blog

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Use Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
      
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: "13.x"
    
    - name: Setup
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        TZ: Asia/Shanghai
      run: |
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

        # set git infomation
        git config --global user.name 'Toby@Github' # 换成你自己的邮箱和名字
        git config --global user.email 'toby.qin@live.com'

        echo Node： `node -v`
        echo npm： `npm -v`
        echo python: `python -V`
        echo pip: `pip -V`

        npm install -g yarn

        # prepare blog
        pip install -r requirements.txt
        python blog.py prepare

        # install dependencies
        yarn global add hexo-cli
        yarn install
  
    - name: Deploy
      run: |
        # publish my blog
        yarn run hexo clean
        yarn run hexo generate
        yarn run hexo deploy
